const Errors = {
  BIG_NAME: 'BIG_NAME',
  EMPTY_NAME: 'EMPTY_NAME',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_ID: 'INVALID_ID',
  NAME_CHARS_INVALID: 'NAME_CHARS_INVALID',
  NAME_WITHOUT_SURNAME: 'NAME_WITHOUT_SURNAME',
  SMALL_NAME: 'SMALL_NAME',
  UNKNOWN: 'UNKNOWN',
  WEAK_PASSWORD: 'WEAK_PASSWORD'
}
export default Errors